In [4]:
import pandas as pd

In [5]:
from IPython.display import display
pd.set_option('display.max_columns', 500)

dataset = pd.read_csv("data/study_results/explanation4_crowd_results.csv")
dataset

HITId                       HITTypeId  \
0    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
1    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
2    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
3    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
4    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
5    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
6    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
7    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
8    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
9    33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
10   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
11   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
12   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
13   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
14   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3D4VT3QYU6RHI7DTKO8ALUYP359J4W   
15   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3D4VT3QYU6RHI7DTKO8ALUYP359J4W   
16   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3D4VT3QYU6RHI7DTKO8ALUYP359J4W   
17   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
18   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
19   33QQ60S6ASUQ78Y3JUJ5VDOVSWC0U6  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
20   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
21   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
22   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
23   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
24   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
25   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
26   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
27   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
28   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
29   3I4E7AFQ2KBI91K05X318MHP8RAJT4  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
..                              ...                             ...   
330  38DCH97KHHE5HLS8OT963H62OKBQJX  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
331  38DCH97KHHE5HLS8OT963H62OKBQJX  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
332  38DCH97KHHE5HLS8OT963H62OKBQJX  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
333  38DCH97KHHE5HLS8OT963H62OKBQJX  3D4VT3QYU6RHI7DTKO8ALUYP359J4W   
334  38DCH97KHHE5HLS8OT963H62OKBQJX  3D4VT3QYU6RHI7DTKO8ALUYP359J4W   
335  38DCH97KHHE5HLS8OT963H62OKBQJX  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
336  38DCH97KHHE5HLS8OT963H62OKBQJX  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
337  38DCH97KHHE5HLS8OT963H62OKBQJX  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
338  38DCH97KHHE5HLS8OT963H62OKBQJX  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
339  38DCH97KHHE5HLS8OT963H62OKBQJX  3GQ1VZELS1H3YJPRV8HELMI8SBIN28   
340  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
341  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
342  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
343  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
344  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
345  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
346  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
347  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
348  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
349  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
350  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
351  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
352  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
353  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PPNWKC4VCQ5GSNF   
354  371DNNCG44ETPKOHET6AJW8BSGGT8U  3YK1EACZ2P5W3I6PP

In [6]:
print("Total number of crowd workers that participated in the study:")
print(len(list(set(list(dataset["WorkerId"])))))

65
55
76


In [9]:
print("Total number of judgments per crowd worker:")
dataset.groupby(['WorkerId']).count().sort_values(['HITId'])

HITId  HITTypeId  Title  Description  Keywords  Reward  \
WorkerId                                                                 
A2YBZFSUD5OP7W      1          1      1            1         1       1   
A2EDER9628S0A       1          1      1            1         1       1   
A2JCK494NV7TFX      1          1      1            1         1       1   
A4W9APAHFWVLO       1          1      1            1         1       1   
A2R8IV2PWFTY00      1          1      1            1         1       1   
A2RRDATXKQ8HHC      1          1      1            1         1       1   
A2UIGDOLX5RV95      1          1      1            1         1       1   
A2VR26FH6ZRMWF      1          1      1            1         1       1   
AKVDY8OXNMQED       1          1      1            1         1       1   
AYCHPTQRYDT7G       1          1      1            1         1       1   
AHPOH7GFQK14J       1          1      1            1         1       1   
A31XT6RPLN6359      1          1      1            1         1       1   
A34DWBBWZRLO1X      1          1      1            1         1       1   
A359ETX78LN74M      1          1      1            1         1       1   
A3B9OZQTE4US3T      1          1      1            1         1       1   
A7204W9E8IR1R       1          1      1            1         1       1   
A3DS5B06ZCD3E3      1          1      1            1         1       1   
A3GIIL73GE2CBQ      1          1      1            1         1       1   
A3OW5EFQ5QFD19      1          1      1            1         1       1   
A3QC57KUVJP5EW      1          1      1            1         1       1   
AP7BOM5KUH8KV       1          1      1            1         1       1   
A2CW8CQCOPMCYA      1          1      1            1         1       1   
A2MQ6VUSKCQ9FH      1          1      1            1         1       1   
A24LC97AU3QC7G      1          1      1            1         1       1   
A1QA5EWFMNKGTA      1          1      1            1         1       1   
A1ZRK6K5JUPJAV      1          1      1            1         1       1   
A1OUUZSD5DD4ZN      1          1      1            1         1       1   
APJJ1HHD2GGFS       1          1      1            1         1       1   
A22051NK9RQ4FV      1          1      1            1         1       1   
A1XLGIFFGB01EU      1          1      1            1         1       1   
A2C2WXXKJOLCZ2      1          1      1            1         1       1   
A1AJG4BGSRPC93      1          1      1            1         1       1   
A144OK7GGOQZKS      1          1      1            1         1       1   
A27PVIL93ZMY46      1          1      1            1         1       1   
A280D4C3U9BXJE      1          1      1            1         1       1   
APGX2WZ59OWDN       1          1      1            1         1       1   
AQORJW4W8U9YU       2          2      2            2         2       2   
A5V3ZMQI0PU3F       2          2      2            2         2       2   
AB66CTVQ90RCV       2          2      2            2         2       2   
A3CFNUD7VR2E1E      2          2      2            2         2       2   

                CreationTime  MaxAssignments  RequesterAnnotation  \
WorkerId                                                            
A2YBZFSUD5OP7W             1               1                    1   
A2EDER9628S0A              1               1                    1   
A2JCK494NV7TFX             1               1                    1   
A4W9APAHFWVLO              1               1                    1   
A2R8IV2PWFTY00             1               1                    1   
A2RRDATXKQ8HHC             1               1                    1   
A2UIGDOLX5RV95             1               1                    1   
A2VR26FH6ZRMWF             1               1                    1   
AKVDY8OXNMQED              1               1                    1   
AYCHPTQRYDT7G              1               1                    1   
AHPOH7GFQK14J              1               1                    1   
A31XT6RPLN

In [7]:
print("Average number of judgments per crowd worker:")
dataset.groupby(['WorkerId']).count().mean()['HITId']

HITId                                 5.538462
HITTypeId                             5.538462
Title                                 5.538462
Description                           5.538462
Keywords                              5.538462
Reward                                5.538462
CreationTime                          5.538462
MaxAssignments                        5.538462
RequesterAnnotation                   5.538462
AssignmentDurationInSeconds           5.538462
AutoApprovalDelayInSeconds            5.538462
Expiration                            5.538462
NumberOfSimilarHITs                   0.000000
LifetimeInSeconds                     0.000000
AssignmentId                          5.538462
AssignmentStatus                      5.538462
AcceptTime                            5.538462
SubmitTime                            5.538462
AutoApprovalTime                      5.538462
ApprovalTime                          5.538462
RejectionTime                         0.000000
RequesterFeed

In [12]:
dataset["Answer.representative"] = "" 

for i in range(len(dataset)):
    if str(dataset["Answer.representativeness.same"].iloc[i]).lower() == "true":
        dataset["Answer.representative"].iloc[i] = "same"
    if str(dataset["Answer.representativeness.none"].iloc[i]).lower() == "true":
        dataset["Answer.representative"].iloc[i] = "none"
        
    if "__aq" in dataset["Input.explanation11"].iloc[i]:
        if str(dataset["Answer.representativeness.summary1"].iloc[i]).lower() == "true":
            dataset["Answer.representative"].iloc[i] = "summary2"
        if str(dataset["Answer.representativeness.summary2"].iloc[i]).lower() == "true":
            dataset["Answer.representative"].iloc[i] = "summary1"
    else:
        if str(dataset["Answer.representativeness.summary1"].iloc[i]).lower() == "true":
            dataset["Answer.representative"].iloc[i] = "summary1"
        if str(dataset["Answer.representativeness.summary2"].iloc[i]).lower() == "true":
            dataset["Answer.representative"].iloc[i] = "summary2"
    

/Users/oanainel/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [16]:
dataset.groupby(["Answer.representative"]).count()

HITId  HITTypeId  Title  Description  Keywords  Reward  \
Answer.representative                                                           
none                      46         46     46           46        46      46   
same                     127        127    127          127       127     127   
summary1                  96         96     96           96        96      96   
summary2                  91         91     91           91        91      91   

                       CreationTime  MaxAssignments  RequesterAnnotation  \
Answer.representative                                                      
none                             46              46                   46   
same                            127             127                  127   
summary1                         96              96                   96   
summary2                         91              91                   91   

                       AssignmentDurationInSeconds  \
Answer.representative                                
none                                            46   
same                                           127   
summary1                                        96   
summary2                                        91   

                       AutoApprovalDelayInSeconds  Expiration  \
Answer.representative                                           
none                                           46          46   
same                                          127         127   
summary1                                       96          96   
summary2                                       91          91   

                       NumberOfSimilarHITs  LifetimeInSeconds  AssignmentId  \
Answer.representative                                                         
none                                     0                  0            46   
same                                     0                  0           127   
summary1                                 0                  0            96   
summary2                                 0                  0            91   

                       WorkerId  AssignmentStatus  AcceptTime  SubmitTime  \
Answer.representative                                                       
none                         46                46          46          46   
same                        127               127         127         127   
summary1                     96                96          96          96   
summary2                     91                91          91          91   

                       AutoApprovalTime  ApprovalTime  RejectionTime  \
Answer.representative                                                  
none                                 46            45              0   
same                                127           126              0   
summary1                             96            96              0   
summary2                             91            90              0   

                       RequesterFeedback  WorkTimeInSeconds  \
Answer.representative                                         
none                                   0                 46   
same                                   0                127   
summary1                               0                 96   
summary2                               0                 91   

                       LifetimeApprovalRate  Last30DaysApprovalRate  \
Answer.representative                                                 
none                                     46                      46   
same                                    127                     127   
summary1                                 96                      96   
summary2                                 91                      91   

                       Last7DaysApprovalRate  Input.youtubeLink  \
Answer.representative                                             
none                                      46        

In [28]:
import numpy as np
table = np.zeros((4, 2))
table = [[55, 109, 78, 118], [46, 127, 96, 91]]
print(table)

[[55, 109, 78, 118], [46, 127, 96, 91]]


In [43]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

stat, p, dof, expected = chi2_contingency([[55, 109, 78, 118], [46, 127, 96, 91]], correction=True)

print('dof=%d' % dof)
print(expected)

# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

dof=3
[[ 50.5 118.   87.  104.5]
 [ 50.5 118.   87.  104.5]]
probability=0.950, critical=7.815, stat=7.525
Independent (fail to reject H0)
significance=0.050, p=0.057
Independent (fail to reject H0)


In [54]:
videos = list(set(list(dataset4["Input.videoStorageLink"])))

for video in videos[0:-3]:
    print(video)
    
    subset1 = dataset1[dataset1["Input.videoStorageLink"] == video]
    subset4 = dataset4[dataset4["Input.videoStorageLink"] == video]
    
    none1 = len(subset1[subset1["Answer.representative"] == "none"])
    none4 = len(subset4[subset4["Answer.representative"] == "none"])
    
    same1 = len(subset1[subset1["Answer.representative"] == "same"])
    same4 = len(subset4[subset4["Answer.representative"] == "same"])
    
    summary11 = len(subset1[subset1["Answer.representative"] == "summary1"])
    summary14 = len(subset4[subset4["Answer.representative"] == "summary1"])
    
    summary21 = len(subset1[subset1["Answer.representative"] == "summary2"])
    summary24 = len(subset4[subset4["Answer.representative"] == "summary2"])
    
    print([[summary11, summary21, same1, none1], [summary14, summary24, same4, none4]])
    stat, p, dof, expected = chi2_contingency([[summary11, summary21, same1, none1], [summary14, summary24, same4, none4]], correction=True)

    print('dof=%d' % dof)
    print(expected)

    # interpret p-value
    alpha = 1.0 - prob
    print('significance=%.3f, p=%.3f' % (alpha, p))
    if p <= alpha:
        print('Dependent (reject H0)')
    else:
        print('Independent (fail to reject H0)')
        
for video in videos[16:]:
    print(video)
    
    subset1 = dataset1[dataset1["Input.videoStorageLink"] == video]
    subset4 = dataset4[dataset4["Input.videoStorageLink"] == video]
    
    none1 = len(subset1[subset1["Answer.representative"] == "none"])
    none4 = len(subset4[subset4["Answer.representative"] == "none"])
    
    same1 = len(subset1[subset1["Answer.representative"] == "same"])
    same4 = len(subset4[subset4["Answer.representative"] == "same"])
    
    summary11 = len(subset1[subset1["Answer.representative"] == "summary1"])
    summary14 = len(subset4[subset4["Answer.representative"] == "summary1"])
    
    summary21 = len(subset1[subset1["Answer.representative"] == "summary2"])
    summary24 = len(subset4[subset4["Answer.representative"] == "summary2"])
    
    print([[summary11, summary21, same1, none1], [summary14, summary24, same4, none4]])
    stat, p, dof, expected = chi2_contingency([[summary11, summary21, same1, none1], [summary14, summary24, same4, none4]], correction=True)

    print('dof=%d' % dof)
    print(expected)

    # interpret p-value
    alpha = 1.0 - prob
    print('significance=%.3f, p=%.3f' % (alpha, p))
    if p <= alpha:
        print('Dependent (reject H0)')
    else:
        print('Independent (fail to reject H0)')

https://storage.googleapis.com/fairview_explanations_videos/nwx96e7qck0.mp4
[[2, 0, 14, 4], [3, 2, 12, 3]]
dof=3
[[ 2.5  1.  13.   3.5]
 [ 2.5  1.  13.   3.5]]
significance=0.050, p=0.476
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/Sv2xibCjjUo.mp4
[[5, 9, 3, 3], [9, 8, 1, 2]]
dof=3
[[7.  8.5 2.  2.5]
 [7.  8.5 2.  2.5]]
significance=0.050, p=0.493
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/SK7GFY5hW6Q.mp4
[[3, 6, 7, 4], [0, 5, 11, 4]]
dof=3
[[1.5 5.5 9.  4. ]
 [1.5 5.5 9.  4. ]]
significance=0.050, p=0.264
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/5FVV7Apeses.mp4
[[3, 1, 13, 3], [2, 3, 11, 4]]
dof=3
[[ 2.5  2.  12.   3.5]
 [ 2.5  2.  12.   3.5]]
significance=0.050, p=0.680
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/Nm4Vzyoe9i4.mp4
[[0, 2, 14, 4], [4, 0, 11, 5]]
dof=3
[[ 2.   1.  12.5  4.5]
 [ 

In [55]:
videos = list(set(list(dataset4["Input.videoStorageLink"])))
  
for video in videos:
    print(video)
    
    subset1 = dataset1[dataset1["Input.videoStorageLink"] == video]
    subset4 = dataset4[dataset4["Input.videoStorageLink"] == video]
    
    none1 = len(subset1[subset1["Answer.representative"] == "none"])
    none4 = len(subset4[subset4["Answer.representative"] == "none"])
    
    same1 = len(subset1[subset1["Answer.representative"] == "same"])
    same4 = len(subset4[subset4["Answer.representative"] == "same"])
    
    summary11 = len(subset1[subset1["Answer.representative"] == "summary1"])
    summary14 = len(subset4[subset4["Answer.representative"] == "summary1"])
    
    summary21 = len(subset1[subset1["Answer.representative"] == "summary2"])
    summary24 = len(subset4[subset4["Answer.representative"] == "summary2"])
    
    print([[summary11, summary21], [summary14, summary24]])
    stat, p, dof, expected = chi2_contingency([[summary11, summary21], [summary14, summary24]], correction=True)

    print('dof=%d' % dof)
    print(expected)

    # interpret p-value
    alpha = 1.0 - prob
    print('significance=%.3f, p=%.3f' % (alpha, p))
    if p <= alpha:
        print('Dependent (reject H0)')
    else:
        print('Independent (fail to reject H0)')

https://storage.googleapis.com/fairview_explanations_videos/nwx96e7qck0.mp4
[[2, 0], [3, 2]]
dof=1
[[1.42857143 0.57142857]
 [3.57142857 1.42857143]]
significance=0.050, p=0.895
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/Sv2xibCjjUo.mp4
[[5, 9], [9, 8]]
dof=1
[[6.32258065 7.67741935]
 [7.67741935 9.32258065]]
significance=0.050, p=0.551
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/SK7GFY5hW6Q.mp4
[[3, 6], [0, 5]]
dof=1
[[1.92857143 7.07142857]
 [1.07142857 3.92857143]]
significance=0.050, p=0.437
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/5FVV7Apeses.mp4
[[3, 1], [2, 3]]
dof=1
[[2.22222222 1.77777778]
 [2.77777778 2.22222222]]
significance=0.050, p=0.708
Independent (fail to reject H0)
https://storage.googleapis.com/fairview_explanations_videos/Nm4Vzyoe9i4.mp4
[[0, 2], [4, 0]]
dof=1
[[1.33333333 0.66666667]
 [2.66666667 1.33333333]]
significan

In [60]:
videos = list(set(list(dataset4["Input.videoStorageLink"])))
  
for video in videos:
    print(video)
    
    subset1 = dataset1[dataset1["Input.videoStorageLink"] == video]
    subset4 = dataset4[dataset4["Input.videoStorageLink"] == video]
    
    none1 = len(subset1[subset1["Answer.representative"] == "none"])
    none4 = len(subset4[subset4["Answer.representative"] == "none"])
    
    same1 = len(subset1[subset1["Answer.representative"] == "same"])
    same4 = len(subset4[subset4["Answer.representative"] == "same"])
    
    summary11 = len(subset1[subset1["Answer.representative"] == "summary1"])
    summary14 = len(subset4[subset4["Answer.representative"] == "summary1"])
    
    summary21 = len(subset1[subset1["Answer.representative"] == "summary2"])
    summary24 = len(subset4[subset4["Answer.representative"] == "summary2"])
    
    oddsratio, pvalue = stats.fisher_exact([[summary11, summary14], [summary21, summary24]])
    print(pvalue)

https://storage.googleapis.com/fairview_explanations_videos/nwx96e7qck0.mp4
1.0
https://storage.googleapis.com/fairview_explanations_videos/Sv2xibCjjUo.mp4
0.4730102747155008
https://storage.googleapis.com/fairview_explanations_videos/SK7GFY5hW6Q.mp4
0.2582417582417581
https://storage.googleapis.com/fairview_explanations_videos/5FVV7Apeses.mp4
0.5238095238095242
https://storage.googleapis.com/fairview_explanations_videos/Nm4Vzyoe9i4.mp4
0.06666666666666675
https://storage.googleapis.com/fairview_explanations_videos/TBGY1x_h53I.mp4
0.004761904761904759
https://storage.googleapis.com/fairview_explanations_videos/XueUJPyDgX8.mp4
0.4827586206896559
https://storage.googleapis.com/fairview_explanations_videos/rxlgs2XT6WA.mp4
0.32258064516128976
https://storage.googleapis.com/fairview_explanations_videos/5cUj7Ta_J_A.mp4
0.062496412885734445
https://storage.googleapis.com/fairview_explanations_videos/q3-eknQ5nlM.mp4
0.720681594686524
https://storage.googleapis.com/fairview_explanations_videos/

In [58]:
import scipy.stats as stats
oddsratio, pvalue = stats.fisher_exact([[55, 109, 78, 118], [46, 127, 96, 91]])

TypeError: fisher_exact() got an unexpected keyword argument 'hybrid'

In [32]:
from scipy.stats import chisquare
chisquare([55, 109, 78, 118], [46, 127, 96, 91], ddof=3)

Power_divergenceResult(statistic=15.698039678568607, pvalue=nan)

In [19]:
videos = list(set(list(dataset1["Input.videoStorageLink"])))

In [24]:
for video in videos:
    print(video)
    subset = dataset1[dataset1["Input.videoStorageLink"] == video]
    print(subset.groupby(["Answer.representative"]).count()["HITId"])
    

https://storage.googleapis.com/fairview_explanations_videos/nwx96e7qck0.mp4
Answer.representative
none         4
same        14
summary1     2
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/Sv2xibCjjUo.mp4
Answer.representative
none        3
same        3
summary1    5
summary2    9
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/SK7GFY5hW6Q.mp4
Answer.representative
none        4
same        7
summary1    3
summary2    6
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/5FVV7Apeses.mp4
Answer.representative
none         3
same        13
summary1     3
summary2     1
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/Nm4Vzyoe9i4.mp4
Answer.representative
none         4
same        14
summary2     2
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/TBGY1x_h53I.mp4
Answer.representative
none        8
same  

In [25]:
for video in videos:
    print(video)
    subset = dataset4[dataset4["Input.videoStorageLink"] == video]
    print(subset.groupby(["Answer.representative"]).count()["HITId"])

https://storage.googleapis.com/fairview_explanations_videos/nwx96e7qck0.mp4
Answer.representative
none         3
same        12
summary1     3
summary2     2
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/Sv2xibCjjUo.mp4
Answer.representative
none        2
same        1
summary1    9
summary2    8
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/SK7GFY5hW6Q.mp4
Answer.representative
none         4
same        11
summary2     5
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/5FVV7Apeses.mp4
Answer.representative
none         4
same        11
summary1     2
summary2     3
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/Nm4Vzyoe9i4.mp4
Answer.representative
none         5
same        11
summary1     4
Name: HITId, dtype: int64
https://storage.googleapis.com/fairview_explanations_videos/TBGY1x_h53I.mp4
Answer.representative
none        8
sa